### ISSUE TITLE
engine:newPico should not be provided

### ISSUE THREAD

**Issue by BTBingham** [Picolab/wrangler#136]

**Comment by LewisThomas** [comment]
Not sure what exactly this means, but the wrangler action createPico is no longer provided from Wrangler and I think that's what this means?

**Comment by BTBingham** [comment]
Yep

Sent from my iPhone

On Mar 1, 2019, at 5:00 PM, LewisToad <notifications@github.com<mailto:notifications@github.com>> wrote:


Not sure what exactly this means, but the wrangler action createPico is no longer provided from Wrangler and I think that's what this means?

**Comment by LewisThomas** [comment]
Done https://github.com/Picolab/pico-engine/pull/456

**Comment by windley** [comment]
Just to be clear. To create a new pico, we use engine:newPico or does Wrangler have a rule to do this? 

I could imagine, for example, that we want Wrangler to do more than the engine does, so we might want to wrap engine:newPico with a Wrangler function even if it doesn't to anything now, so that in the future we can add other items to it.

**Comment by LewisThomas** [comment]
A KRL developer should use Wrangler to create a new pico by raising an event. They should not be calling engine:newPico(), for a multitude of reasons.

**Comment by windley** [comment]
Good. So we've made engine:newPico unavailable generally (i.e. not provided) and Wrangler is the preferred method.
