### ISSUE TITLE
subscriptions to other KRE's

### ISSUE THREAD

**Issue by burdettadam** [Picolab/wrangler#74]
subscriptions will need to store more information to allow a pico to communicate to a pico on a different rules engine.

**Comment by b1conrad** [comment]
the other KRE could, of course, even be one of the new version. an event is an event, etc

**Comment by windley** [comment]
There's a larger discussion here. Moving picos from one KRE (pico engine) to another will require that picos be discovered by name rather than by ESL. That's one reason I've been pushing for lookups, etc. to be done by name where we can. We'll have to do more of it in the future. 

How that discovery works is the big question. I dislike using a central registration system. There are several things that might be used instead: blockchain or IPFS.

**Comment by burdettadam** [comment]
I think we could accomplish subscriptions between picos on different kre's by treating subscriptions events as api calls and storing url information. we could store kre instance information to identify if both picos are on the same instance. if they are not on the same kre, default to using a stored api (url) instead of an eci, to raise events to. we would need to store an api to call functions on the subscriber as well.

**Comment by windley** [comment]
So, in the event of a move, each subscriber would be notified of the new ESL and they would be responsible for update?

**Comment by burdettadam** [comment]
closing and combining in #99. I think this may have been done by 0joshuaolson1.

**Comment by 0joshuaolson1** [comment]
With other Node pico engines at least.
